language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test:ci
  - npm run build:ci
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist/courses
  on:
    branch: master
